import { IShoppingAction } from "../ts/interfaces/global_interfaces";

export const TYPES: IShoppingAction  = {
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_ONE_FROM_CART: 'REMOVE_ONE_FROM_CART',
    REMOVE_ALL_FROM_CART: 'REMOVE_ALL_FROM_CART',
    UPDATE_CART: 'UPDATE_CART',
    CLEAR_CART: 'CLEAR_CART',
    ADD_TO_WISHLIST: 'ADD_TO_WISHLIST',
    REMOVE_FROM_WISHLIST: 'REMOVE_FROM_WISHLIST',
    UPDATE_WISHLIST: 'UPDATE_WISHLIST',
    CLEAR_WISHLIST: 'CLEAR_WISHLIST',
}